version: "2.1"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    cpu_shares: 10
    mem_limit: 524288000
    ports:
      - "80:80"
      - "443:443"
    networks:
      - docker_net
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./docker/proxy/htpasswd:/etc/nginx/htpasswd
      - ./docker/proxy/certs:/etc/nginx/certs:ro
      - ./proxy/timeout.conf:/etc/nginx/conf.d/timeout.conf

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    restart: always
    cpu_shares: 10
    mem_limit: 524288000
    networks:
      - docker_net
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    restart: always
    cpu_shares: 10
    mem_limit: 524288000
    networks:
      - docker_net
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/proxy/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen

networks:
  docker_net:
    driver: bridge